apiVersion: apps/v1
kind: Deployment
metadata:
  name: mylab27
  labels:
    app: webnginx
spec:
  replicas: 4
  selector:
    matchLabels:
      app: nginxwebpod2
  template:
    metadata:
      labels:
        app: nginxwebpod2
    spec:
      containers:
      - name: nginx
        image: trimmerr/lab27:v0.1 
        imagePullPolicy: Always 
---
apiVersion: v1 
kind: Service 
metadata: 
    name: mylab27 
spec: 
   selector: 
     app: nginxwebpod2 
   type: NodePort
   ports: 
        - protocol: TCP 
          port: 80 
          targetPort: 80
